// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Context {
    /**
     * Creates a new Context instance.
     * @param {Partial<Context>} [$$source = {}] - The source object to create the Context.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Context instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Context}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Context(/** @type {Partial<Context>} */($$parsedSource));
    }
}
