// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Your "Super Vanilla" Dispatcher (same logic as v2)
 * @param {string} funcName
 * @param {any[]} args
 * @param {string[]} types
 * @returns {$CancellablePromise<any>}
 */
export function CallGo(funcName, args, types) {
    return $Call.ByID(1899458039, funcName, args, types);
}

/**
 * In v3, Services can have an OnStartup method that receives the app instance
 * @param {application$0.Context | null} ctx
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(ctx) {
    return $Call.ByID(2232168041, ctx);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function SayHello(name) {
    return $Call.ByID(1304006192, name);
}
